using CommunityCar.Domain.Common;
using CommunityCar.Domain.Entities.Podcasts.Common;
using CommunityCar.Domain.Entities.Podcasts.Engagement;

namespace CommunityCar.Domain.Entities.Podcasts.Shows;

/// <summary>
/// Individual podcast episode
/// </summary>
public class PodcastEpisode : BaseEntity
{
    public Guid PodcastShowId { get; set; }
    public PodcastShow PodcastShow { get; set; } = null!;
    
    // Basic Info
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? Slug { get; set; }
    public string? Summary { get; set; }
    public string? ShowNotes { get; set; }
    
    // Episode Number
    public int? SeasonNumber { get; set; }
    public int EpisodeNumber { get; set; }
    
    // Media
    public string AudioUrl { get; set; } = string.Empty;
    public string? VideoUrl { get; set; }
    public string? ThumbnailUrl { get; set; }
    public string? OriginalFileName { get; set; }
    public long FileSizeBytes { get; set; }
    public TimeSpan Duration { get; set; }
    
    // Type & Status
    public EpisodeType Type { get; set; } = EpisodeType.Full;
    public EpisodeStatus Status { get; set; } = EpisodeStatus.Draft;
    public ExplicitContent ExplicitContent { get; set; } = ExplicitContent.Clean;
    
    // Publishing
    public DateTime? ScheduledPublishAt { get; set; }
    public DateTime? PublishedAt { get; set; }
    
    // Stats
    public long PlayCount { get; set; }
    public int UniqueListeners { get; set; }
    public int DownloadCount { get; set; }
    public int LikeCount { get; set; }
    public int CommentCount { get; set; }
    public int ShareCount { get; set; }
    public double AverageListenPercent { get; set; }
    public TimeSpan AverageListenTime { get; set; }
    
    // Settings
    public bool AllowComments { get; set; } = true;
    public bool AllowDownloads { get; set; } = true;
    
    // Chapters/Timestamps
    public string? ChaptersJson { get; set; }
    
    // Transcript
    public string? TranscriptJson { get; set; }
    public string? TranscriptUrl { get; set; }
    public bool HasAutoGeneratedTranscript { get; set; }
    
    // Processing
    public bool IsProcessed { get; set; }
    public string? ProcessingError { get; set; }
    public DateTime? ProcessedAt { get; set; }
    
    // Guests
    public string? GuestsJson { get; set; }
    
    // Links & Resources
    public string? LinksJson { get; set; }
    
    // SEO
    public string? MetaTitle { get; set; }
    public string? MetaDescription { get; set; }
    
    // Navigation
    public List<EpisodeComment> Comments { get; set; } = [];
    public List<EpisodeReaction> Reactions { get; set; } = [];
    public List<EpisodePlay> Plays { get; set; } = [];
    public List<EpisodeChapter> Chapters { get; set; } = [];
}
