using CommunityCar.Domain.Entities.Community.Reviews;

namespace CommunityCar.Application.DTOs.Response.Community.Reviews;

public record ReviewDto(
    Guid Id,
    Guid AuthorId,
    string AuthorName,
    string? AuthorAvatarUrl,
    string Title,
    string? Slug,
    string Content,
    ReviewSubjectType SubjectType,
    string? SubjectId,
    string? CarMake,
    string? CarModel,
    int? CarYear,
    string? CarTrim,
    OwnershipStatus? OwnershipStatus,
    int? OwnershipMonths,
    int? MilesDriven,
    int OverallRating,
    int? PerformanceRating,
    int? ComfortRating,
    int? ReliabilityRating,
    int? ValueRating,
    int? FuelEconomyRating,
    int? StyleRating,
    int? TechnologyRating,
    List<string> Pros,
    List<string> Cons,
    string? CoverImageUrl,
    List<ReviewMediaDto> Media,
    ReviewStatus Status,
    DateTime? PublishedAt,
    int ViewCount,
    int HelpfulCount,
    int CommentCount,
    bool IsVerifiedPurchase,
    bool IsExpertReview,
    bool IsFeatured,
    bool? CurrentUserFoundHelpful,
    DateTime CreatedAt
);
