import { UserActionFlags } from '../common/user-action.interface';
import { VideoOrientation, VideoType, VideoStatus, VideoVisibility, ContentRating, VideoQuality } from './enums/video-enums';

/**
 * Main Video interface
 * Represents a video with full social media features
 */
export interface Video {
  id: string;
  channelId: string;
  channel: VideoChannel;
  
  // Basic Info
  title: string;
  description: string | null;
  slug: string | null;
  
  // Media
  videoUrl: string;
  thumbnailUrl: string | null;
  previewGifUrl: string | null;
  originalFileName: string | null;
  fileSizeBytes: number;
  
  // Video Properties
  duration: string; // TimeSpan as string (e.g., "00:05:30")
  width: number;
  height: number;
  orientation: VideoOrientation;
  aspectRatio: number;
  frameRate: number;
  codec: string | null;
  
  // Available Qualities
  availableQualities: VideoQuality[];
  qualityUrls: Record<VideoQuality, string> | null;
  
  // Type & Status
  type: VideoType;
  status: VideoStatus;
  visibility: VideoVisibility;
  contentRating: ContentRating;
  
  // Scheduling
  scheduledPublishAt: string | null;
  publishedAt: string | null;
  expiresAt: string | null;
  
  // Categorization
  categoryId: string | null;
  categoryName: string | null;
  tags: string[];
  hashtags: string[];
  
  // Location
  locationName: string | null;
  latitude: number | null;
  longitude: number | null;
  
  // Engagement Stats
  viewCount: number;
  uniqueViewers: number;
  likeCount: number;
  dislikeCount: number;
  commentCount: number;
  shareCount: number;
  saveCount: number;
  downloadCount: number;
  averageWatchPercent: number;
  averageWatchTime: string; // TimeSpan as string
  
  // Settings
  allowComments: boolean;
  allowDuets: boolean;
  allowStitches: boolean;
  allowDownloads: boolean;
  showLikeCount: boolean;
  isPinned: boolean;
  
  // Monetization
  isMonetized: boolean;
  hasAds: boolean;
  isSponsoredContent: boolean;
  sponsorName: string | null;
  estimatedEarnings: number | null;
  
  // Music/Audio
  soundId: string | null;
  sound: VideoSound | null;
  originalAudioUrl: string | null;
  useOriginalAudio: boolean;
  
  // Related Content
  duetOfVideoId: string | null;
  duetOfVideo: VideoRelated | null;
  stitchOfVideoId: string | null;
  stitchOfVideo: VideoRelated | null;
  replyToVideoId: string | null;
  replyToVideo: VideoRelated | null;
  
  // SEO
  metaTitle: string | null;
  metaDescription: string | null;
  
  // Processing
  isProcessed: boolean;
  processingError: string | null;
  processedAt: string | null;
  
  // AI Analysis
  aiTags: string[] | null;
  transcript: VideoTranscript[] | null;
  captions: VideoCaption[] | null;
  hasAutoGeneratedCaptions: boolean;
  
  // User Actions
  userActions: UserActionFlags | null;
  
  // Timestamps
  createdAt: string;
  updatedAt: string | null;
}

/**
 * Video Channel (Creator)
 */
export interface VideoChannel {
  id: string;
  userId: string;
  handle: string;
  displayName: string;
  bio: string | null;
  avatarUrl: string | null;
  bannerUrl: string | null;
  websiteUrl: string | null;
  isVerified: boolean;
  subscriberCount: number;
  videoCount: number;
  totalViews: number;
}

/**
 * Video Sound/Music
 */
export interface VideoSound {
  id: string;
  title: string;
  artist: string | null;
  duration: string;
  audioUrl: string;
  coverImageUrl: string | null;
  isOriginal: boolean;
  usageCount: number;
}

/**
 * Related Video (for duets, stitches, replies)
 */
export interface VideoRelated {
  id: string;
  title: string;
  thumbnailUrl: string | null;
  channelHandle: string;
  channelDisplayName: string;
}

/**
 * Video Transcript
 */
export interface VideoTranscript {
  startTime: number; // seconds
  endTime: number; // seconds
  text: string;
  confidence: number;
}

/**
 * Video Caption
 */
export interface VideoCaption {
  language: string;
  url: string;
  isAutoGenerated: boolean;
}
