import { EpisodeType, EpisodeStatus, ExplicitContent } from './enums/podcast-enums';

/**
 * Podcast Episode interface
 * Represents an individual podcast episode
 */
export interface PodcastEpisode {
  id: string;
  podcastShowId: string;
  podcastTitle: string;
  podcastCoverImageUrl: string | null;
  
  // Basic Info
  title: string;
  description: string | null;
  slug: string | null;
  summary: string | null;
  showNotes: string | null;
  
  // Episode Number
  seasonNumber: number | null;
  episodeNumber: number;
  
  // Media
  audioUrl: string;
  videoUrl: string | null;
  thumbnailUrl: string | null;
  originalFileName: string | null;
  fileSizeBytes: number;
  duration: string; // TimeSpan as string
  
  // Type & Status
  type: EpisodeType;
  status: EpisodeStatus;
  explicitContent: ExplicitContent;
  
  // Publishing
  scheduledPublishAt: string | null;
  publishedAt: string | null;
  
  // Stats
  playCount: number;
  uniqueListeners: number;
  downloadCount: number;
  likeCount: number;
  commentCount: number;
  shareCount: number;
  averageListenPercent: number;
  averageListenTime: string; // TimeSpan
  
  // Settings
  allowComments: boolean;
  allowDownloads: boolean;
  
  // Chapters/Timestamps
  chapters: EpisodeChapter[];
  
  // Transcript
  transcript: EpisodeTranscript | null;
  transcriptUrl: string | null;
  hasAutoGeneratedTranscript: boolean;
  
  // Processing
  isProcessed: boolean;
  processingError: string | null;
  processedAt: string | null;
  
  // Guests
  guests: EpisodeGuest[];
  
  // Links & Resources
  links: EpisodeLink[];
  
  // SEO
  metaTitle: string | null;
  metaDescription: string | null;
  
  // Timestamps
  createdAt: string;
  updatedAt: string | null;
}

/**
 * Episode Chapter
 */
export interface EpisodeChapter {
  id: string;
  title: string;
  description: string | null;
  imageUrl: string | null;
  url: string | null;
  startTime: string; // TimeSpan
  endTime: string | null; // TimeSpan
}

/**
 * Episode Guest
 */
export interface EpisodeGuest {
  name: string;
  bio: string | null;
  avatarUrl: string | null;
  websiteUrl: string | null;
  twitterUrl: string | null;
}

/**
 * Episode Link/Resource
 */
export interface EpisodeLink {
  title: string;
  url: string;
  description: string | null;
}

/**
 * Episode Transcript
 */
export interface EpisodeTranscript {
  segments: TranscriptSegment[];
}

/**
 * Transcript Segment
 */
export interface TranscriptSegment {
  startTime: number; // seconds
  endTime: number; // seconds
  text: string;
  speaker: string | null;
}
