using CommunityCar.Domain.Common;
using CommunityCar.Domain.Entities.Videos.Channels;
using CommunityCar.Domain.Entities.Videos.Common;

namespace CommunityCar.Domain.Entities.Videos.Playlists;

public class Playlist : BaseEntity
{
    public Guid ChannelId { get; set; }
    public Channel Channel { get; set; } = null!;
    
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? Slug { get; set; }
    public string? ThumbnailUrl { get; set; }
    
    public VideoVisibility Visibility { get; set; } = VideoVisibility.Public;
    
    public int VideoCount { get; set; }
    public TimeSpan TotalDuration { get; set; }
    public long TotalViews { get; set; }
    
    public bool IsAutoGenerated { get; set; }
    public bool IsFeatured { get; set; }
    
    public List<PlaylistItem> Items { get; set; } = [];
}
