using CommunityCar.Domain.Entities.Videos.Common;
using CommunityCar.Domain.Entities.Videos.Channels;

namespace CommunityCar.Application.DTOs.Response.Videos;

// Video DTOs
public record VideoDto(
    Guid Id,
    Guid ChannelId,
    string ChannelHandle,
    string ChannelDisplayName,
    string? ChannelAvatarUrl,
    bool ChannelIsVerified,
    string Title,
    string? Description,
    string Slug,
    string VideoUrl,
    string? ThumbnailUrl,
    string? PreviewGifUrl,
    TimeSpan Duration,
    int? Width,
    int? Height,
    VideoOrientation Orientation,
    List<VideoQuality> AvailableQualities,
    VideoType Type,
    VideoStatus Status,
    VideoVisibility Visibility,
    ContentRating ContentRating,
    DateTime? PublishedAt,
    string? CategoryName,
    List<string> Tags,
    List<string> Hashtags,
    string? LocationName,
    long ViewCount,
    long LikeCount,
    long CommentCount,
    long ShareCount,
    long SaveCount,
    bool AllowComments,
    bool AllowDuets,
    bool AllowDownloads,
    bool IsMonetized,
    bool IsSponsoredContent,
    string? SponsorName,
    Guid? SoundId,
    string? SoundTitle,
    string? SoundArtist,
    Guid? DuetOfVideoId,
    Guid? StitchOfVideoId,
    bool HasAutoGeneratedCaptions,
    DateTime CreatedAt
);

public record VideoListItemDto(
    Guid Id,
    string Title,
    string? ThumbnailUrl,
    TimeSpan Duration,
    VideoType Type,
    string ChannelHandle,
    string ChannelDisplayName,
    string? ChannelAvatarUrl,
    bool ChannelIsVerified,
    long ViewCount,
    long LikeCount,
    DateTime? PublishedAt
);

public record VideoFeedItemDto(
    Guid Id,
    string Title,
    string? Description,
    string VideoUrl,
    string? ThumbnailUrl,
    TimeSpan Duration,
    VideoType Type,
    VideoOrientation Orientation,
    Guid ChannelId,
    string ChannelHandle,
    string ChannelDisplayName,
    string? ChannelAvatarUrl,
    bool ChannelIsVerified,
    long ViewCount,
    long LikeCount,
    long CommentCount,
    long ShareCount,
    bool IsLikedByUser,
    bool IsSavedByUser,
    bool IsFollowingChannel,
    Guid? SoundId,
    string? SoundTitle,
    List<string> Hashtags,
    DateTime? PublishedAt
);

public record TrendingHashtagDto(
    string Tag,
    int VideoCount,
    int TotalViews,
    int TrendRank
);

public record VideoCategoryDto(
    Guid Id,
    string Name,
    string Description,
    string Slug,
    string? IconUrl,
    int VideoCount,
    bool IsFeatured
);

public record VideoUploadResponse(
    Guid VideoId,
    string UploadUrl,
    string? ThumbnailUploadUrl,
    DateTime ExpiresAt
);

// Channel DTOs
public record ChannelDto(
    Guid Id,
    Guid UserId,
    string Handle,
    string DisplayName,
    string? Bio,
    string? AvatarUrl,
    string? BannerUrl,
    string? WebsiteUrl,
    ChannelStatus Status,
    ChannelTier Tier,
    bool IsVerified,
    int SubscriberCount,
    int VideoCount,
    int TotalViews,
    bool AllowComments,
    bool ShowSubscriberCount,
    bool AllowDuets,
    string? InstagramUrl,
    string? TwitterUrl,
    string? Country,
    List<string> ContentCategories,
    DateTime CreatedAt
);

public record ChannelListItemDto(
    Guid Id,
    string Handle,
    string DisplayName,
    string? AvatarUrl,
    bool IsVerified,
    int SubscriberCount,
    int VideoCount
);

public record ChannelStatsDto(
    int TotalSubscribers,
    int SubscribersThisMonth,
    int TotalVideos,
    int TotalViews,
    int ViewsThisMonth,
    int TotalLikes,
    int TotalComments,
    TimeSpan TotalWatchTime,
    decimal TotalEarnings,
    decimal EarningsThisMonth,
    List<DailyStatDto> Last30Days
);

public record DailyStatDto(
    DateTime Date,
    int Views,
    int Subscribers,
    decimal Earnings
);

// Engagement DTOs
public record CommentDto(
    Guid Id,
    Guid VideoId,
    Guid UserId,
    string UserName,
    string? UserAvatarUrl,
    string Content,
    Guid? ParentId,
    int LikeCount,
    int ReplyCount,
    bool IsPinned,
    bool IsLiked,
    bool IsCreatorReplied,
    List<CommentDto>? Replies,
    DateTime CreatedAt
);

public record ReactionDto(
    Guid Id,
    ReactionType Type
);

public record VideoSummaryDto(
    Guid Id,
    string Title,
    string? ThumbnailUrl,
    TimeSpan Duration,
    string ChannelName,
    long ViewCount
);

public record SavedVideoDto(
    Guid Id,
    Guid VideoId,
    VideoSummaryDto Video,
    Guid? CollectionId,
    DateTime SavedAt
);

public record VideoCollectionDto(
    Guid Id,
    string Name,
    string? Description,
    bool IsPrivate,
    int VideoCount,
    string? CoverImageUrl,
    DateTime CreatedAt
);

public record ShareResponseDto(
    string ShareUrl
);

// LiveStream DTOs
public record LiveStreamDto(
    Guid Id,
    Guid ChannelId,
    string ChannelName,
    string Title,
    string? Description,
    string? ThumbnailUrl,
    string Status,
    DateTime? ScheduledStartTime,
    DateTime? StartedAt,
    DateTime? EndedAt,
    int ViewerCount,
    int PeakViewerCount,
    int TotalViews
);

public record LiveStreamListItemDto(
    Guid Id,
    string Title,
    string? ThumbnailUrl,
    Guid ChannelId,
    string ChannelName,
    string? ChannelAvatarUrl,
    string Status,
    int ViewerCount,
    DateTime? ScheduledStartTime,
    DateTime? StartedAt
);

public record StartLiveStreamResponse(
    Guid LiveStreamId,
    string StreamUrl,
    string StreamKey,
    string PlaybackUrl
);

public record LiveStreamChatDto(
    Guid Id,
    Guid LiveStreamId,
    Guid UserId,
    string UserName,
    string? UserAvatarUrl,
    string Message,
    bool IsPinned,
    bool IsModerator,
    DateTime SentAt
);

public record LiveStreamGiftDto(
    Guid Id,
    Guid LiveStreamId,
    Guid UserId,
    string UserName,
    string GiftType,
    int GiftCount,
    int CoinValue,
    DateTime SentAt
);

public record GiftTypeDto(
    string Id,
    string Name,
    string IconUrl,
    int CoinCost,
    string? Animation
);

// Sound DTOs
public record SoundDto(
    Guid Id,
    string Title,
    string? Artist,
    string AudioUrl,
    int DurationSeconds,
    string? Genre,
    int UseCount,
    bool IsFeatured,
    DateTime CreatedAt
);

public record SoundListItemDto(
    Guid Id,
    string Title,
    string? Artist,
    string AudioUrl,
    int DurationSeconds,
    int UseCount
);

public record TrendingSoundDto(
    Guid Id,
    string Title,
    string? Artist,
    string AudioUrl,
    int DurationSeconds,
    int UseCount,
    int TrendRank
);
