using CommunityCar.Domain.Common;
using CommunityCar.Domain.Entities.Videos.Channels;
using CommunityCar.Domain.Entities.Videos.Common;
using CommunityCar.Domain.Entities.Videos.Engagement;

namespace CommunityCar.Domain.Entities.Videos.Content;

/// <summary>
/// Enhanced video entity with full social media features
/// </summary>
public class Video : BaseEntity
{
    public Guid ChannelId { get; set; }
    public Channel Channel { get; set; } = null!;
    
    // Basic Info
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? Slug { get; set; }
    
    // Media
    public string VideoUrl { get; set; } = string.Empty;
    public string? ThumbnailUrl { get; set; }
    public string? PreviewGifUrl { get; set; }
    public string? OriginalFileName { get; set; }
    public long FileSizeBytes { get; set; }
    
    // Video Properties
    public TimeSpan Duration { get; set; }
    public int Width { get; set; }
    public int Height { get; set; }
    public VideoOrientation Orientation { get; set; }
    public double AspectRatio { get; set; }
    public int FrameRate { get; set; }
    public string? Codec { get; set; }
    
    // Available Qualities
    public List<VideoQuality> AvailableQualities { get; set; } = [];
    public string? QualityUrlsJson { get; set; }
    
    // Type & Status
    public VideoType Type { get; set; } = VideoType.Standard;
    public VideoStatus Status { get; set; } = VideoStatus.Draft;
    public VideoVisibility Visibility { get; set; } = VideoVisibility.Public;
    public ContentRating ContentRating { get; set; } = ContentRating.General;
    
    // Scheduling
    public DateTime? ScheduledPublishAt { get; set; }
    public DateTime? PublishedAt { get; set; }
    public DateTime? ExpiresAt { get; set; }
    
    // Categorization
    public Guid? CategoryId { get; set; }
    public VideoCategory? Category { get; set; }
    public List<string> Tags { get; set; } = [];
    public List<string> Hashtags { get; set; } = [];
    
    // Location
    public string? LocationName { get; set; }
    public double? Latitude { get; set; }
    public double? Longitude { get; set; }
    
    // Engagement Stats
    public long ViewCount { get; set; }
    public int UniqueViewers { get; set; }
    public int LikeCount { get; set; }
    public int DislikeCount { get; set; }
    public int CommentCount { get; set; }
    public int ShareCount { get; set; }
    public int SaveCount { get; set; }
    public int DownloadCount { get; set; }
    public double AverageWatchPercent { get; set; }
    public TimeSpan AverageWatchTime { get; set; }
    
    // Settings
    public bool AllowComments { get; set; } = true;
    public bool AllowDuets { get; set; } = true;
    public bool AllowStitches { get; set; } = true;
    public bool AllowDownloads { get; set; } = true;
    public bool ShowLikeCount { get; set; } = true;
    public bool IsPinned { get; set; }
    
    // Monetization
    public bool IsMonetized { get; set; }
    public bool HasAds { get; set; }
    public bool IsSponsoredContent { get; set; }
    public string? SponsorName { get; set; }
    public decimal? EstimatedEarnings { get; set; }
    
    // Music/Audio
    public Guid? SoundId { get; set; }
    public Sound? Sound { get; set; }
    public string? OriginalAudioUrl { get; set; }
    public bool UseOriginalAudio { get; set; } = true;
    
    // Related Content
    public Guid? DuetOfVideoId { get; set; }
    public Video? DuetOfVideo { get; set; }
    public Guid? StitchOfVideoId { get; set; }
    public Video? StitchOfVideo { get; set; }
    public Guid? ReplyToVideoId { get; set; }
    public Video? ReplyToVideo { get; set; }
    
    // SEO
    public string? MetaTitle { get; set; }
    public string? MetaDescription { get; set; }
    
    // Processing
    public bool IsProcessed { get; set; }
    public string? ProcessingError { get; set; }
    public DateTime? ProcessedAt { get; set; }
    
    // AI Analysis
    public string? AITagsJson { get; set; }
    public string? TranscriptJson { get; set; }
    public string? CaptionsJson { get; set; }
    public bool HasAutoGeneratedCaptions { get; set; }
    
    // Navigation
    public List<VideoComment> Comments { get; set; } = [];
    public List<VideoReaction> Reactions { get; set; } = [];
    public List<VideoView> Views { get; set; } = [];
    public List<VideoMention> Mentions { get; set; } = [];
}
