import { VideoVisibility } from '../enums/video-enums';

/**
 * Playlist
 */
export interface Playlist {
  id: string;
  channelId: string;
  channelHandle: string;
  channelDisplayName: string;
  channelAvatarUrl: string | null;
  title: string;
  description: string | null;
  slug: string | null;
  thumbnailUrl: string | null;
  visibility: VideoVisibility;
  videoCount: number;
  totalDuration: string; // TimeSpan
  totalViews: number;
  isAutoGenerated: boolean;
  isFeatured: boolean;
  items: PlaylistItem[];
  createdAt: string;
  updatedAt: string | null;
}

/**
 * Playlist Item
 */
export interface PlaylistItem {
  id: string;
  playlistId: string;
  videoId: string;
  video: PlaylistVideo;
  sortOrder: number;
  addedAt: string;
}

/**
 * Playlist Video
 */
export interface PlaylistVideo {
  id: string;
  title: string;
  thumbnailUrl: string | null;
  duration: string;
  channelHandle: string;
  channelDisplayName: string;
  viewCount: number;
}

/**
 * Playlist List Item
 */
export interface PlaylistListItem {
  id: string;
  title: string;
  description: string | null;
  thumbnailUrl: string | null;
  visibility: VideoVisibility;
  videoCount: number;
  totalDuration: string;
  channelHandle: string;
  channelDisplayName: string;
  createdAt: string;
}

/**
 * Playlist Filter
 */
export interface PlaylistFilter {
  searchTerm?: string;
  channelId?: string;
  visibility?: VideoVisibility;
  isFeatured?: boolean;
  sortBy?: string;
  page?: number;
  pageSize?: number;
}
